

version: '3.9'
services:
  laravel-openapi-test_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/html'
    networks:
      - laravel-openapi-test_network
  laravel-openapi-test_db:
    image: 'mysql:8.0.28'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'laravel-openapi-test'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - laravel-openapi-test_network

networks:
  laravel-openapi-test_network:
    driver: bridge
